apiVersion: apps/v1
kind: Deployment
metadata:
  name: kopysza
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kopysza
  template:
    metadata:
      labels:
        app: kopysza
    spec:
      containers:
      - image: okteto.dev/kopysza:latest
        name: kopysza
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "939803da-a5ae-4afa-b505-d2c53e1239b6"
        - name: Vless_Path
          value: "/gyhgy8754"
        - name: Vmess_UUID
          value: "939803da-a5ae-4afa-b505-d2c53e1239b6"
        - name: Vmess_Path
          value: "/knitce6585"
        - name: Share_Path
          value: "/v2link"
